spring:
  application:
    name: DocMailSender
  datasource:
    url: jdbc:postgresql://localhost:5435/flagman_docsmail
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: "smtp.mail.ru"
  kafka:
    bootstrap-servers:
      - localhost:9092
    #      - localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8081

flagman:
  mail:
    password: ${SMTP_MAILRU_PASSWORD}
    sender: "docs.flagman@mail.ru"